export const HELP_DRAWER_AVAILABLE_SCREENS = {
    TEMPLATES_JSON: 'TEMPLATES_JSON',
    INTERNAL_SQUADS_GRID: 'INTERNAL_SQUADS_GRID',
    EXTERNAL_SQUADS_GRID: 'EXTERNAL_SQUADS_GRID'
} as const

export type THelpDrawerAvailableScreen =
    (typeof HELP_DRAWER_AVAILABLE_SCREENS)[keyof typeof HELP_DRAWER_AVAILABLE_SCREENS]
