export const HELP_DRAWER_AVAILABLE_SCREENS = {
    EDITOR_TEMPLATES_XRAY_JSON: 'EDITOR_TEMPLATES_XRAY_JSON',
    PAGE_INTERNAL_SQUADS: 'PAGE_INTERNAL_SQUADS',
    PAGE_EXTERNAL_SQUADS: 'PAGE_EXTERNAL_SQUADS',
    PAGE_HOSTS: 'PAGE_HOSTS',
    PAGE_CONFIG_PROFILES: 'PAGE_CONFIG_PROFILES'
} as const

export type THelpDrawerAvailableScreen =
    (typeof HELP_DRAWER_AVAILABLE_SCREENS)[keyof typeof HELP_DRAWER_AVAILABLE_SCREENS]
